#!/usr/bin/env fish

function __{{.ProgramName}}_debug
    set -l file "$COMP_DEBUG_FILE"
    if test -n "$file"
        echo "$argv" >> $file
    end
end

function __fish_{{.ProgramName}}_complete_command
  __{{.ProgramName}}_debug "Starting __{{.ProgramName}}_complete_command"

  set -l args (commandline -op)

  __{{.ProgramName}}_debug "args: $args"

  $args --mcli-generate-completion fish
end

complete -fc server -a "(__fish_{{.ProgramName}}_complete_command)"
